### ISSUE TITLE
RaceID3 using 10x datasets

### ISSUE THREAD

**Issue by seigfried** [dgrun/RaceID3_StemID2_package#1]
Hello I wish to cluster my single cell 10x data using RaceID3. However, I cannot load my 10x data into RaceID using their function SCseq

10x gave me 3 files:
1) barcodes.tsv.gz
2) features.tsv.gz
3) matrix.mtx.gz

I tried using the Matrix package in R as given on the 10x website.

```
library(Matrix)
matrix_dir = "C:/Users/s/Downloads/"
barcode.path <- paste0(matrix_dir, "barcodes.tsv.gz")
features.path <- paste0(matrix_dir, "features.tsv.gz")
matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
mat <- readMM(file = matrix.path)
feature.names = read.delim(features.path, 
                       header = FALSE,
                       stringsAsFactors = FALSE)
barcode.names = read.delim(barcode.path, 
                       header = FALSE,
                       stringsAsFactors = FALSE)
colnames(mat) = barcode.names$V1
rownames(mat) = feature.names$V1
```

And it fails to allocate a huge amount of memory

```
> sc <- SCseq(mat)
Error: cannot allocate vector of size 6823.1 Gb
```

I also tried using Seurat's Read10X function :

```
library(Seurat)
library(RaceID)
pbmc.data <- Read10X(data.dir = "C:/Users/s/Downloads/")
sc <- SCseq(pbmc.data)
```

Here is my pbmc.data

```
> pbmc.data
33694 x 27179520 sparse Matrix of class "dgCMatrix"
```

This is the error i get :

```
sc <- SCseq(pbmc.data)
Error in asMethod(object) : Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

I understand that RaceID requires a sparse matrix which I am already providing. Can you please explain? Thank you!

**Comment by dgrun** [comment]
Hi,

please try the following code:

require(Matrix)
require(RaceID)
x <- readMM("matrix.mtx")
f <- read.csv("features.tsv",sep="\t",header=FALSE)
b <- read.csv("barcodes.tsv",sep="\t",header=FALSE)
rownames(x) <- f[,1]
colnames(x) <- b[,1]

sc <- SCseq(x)



This should work unless you don't have sufficient memory.
