### ISSUE TITLE
how to convert seurat object to scseq object

### ISSUE THREAD

**Issue by JingAvaWang** [dgrun/RaceID3_StemID2_package#2]
hi, I want to convert a seurat object to scseq object and conduct downstream analysis, do you know any method could achieve it ?

**Comment by dgrun** [comment]
Hi, 

this is not directly possible. I would just run RaceID on the same count table used to create the Seurat object.

**Comment by JingAvaWang** [comment]
thanks for your kind reply, I will just input the raw data.
