### ISSUE TITLE
Error in cluster::pam(as.dist(x), k) : NA values in the dissimilarity matrix not allowed.

### ISSUE THREAD

**Issue by saramasarone** [dgrun/RaceID3_StemID2_package#3]
Hi 😊, 

I am trying to use a count matrix (.tsv dense matrix) into this function sc <- ### SCseq() but it does not seem to be able to read it. Therefore, I uploaded it first as data.table and then passed it into the function and it seems to be fine (why?). 
However, after filtering the cells and computing a distance matrix I get the following error:
### Error in cluster::pam(as.dist(x), k) : NA values in the dissimilarity matrix not allowed.

What do you think is causing the issue and how do I fix it?

I attached the screenshot for more info. 
<img width="1440" alt="Screenshot 2020-02-28 at 10 58 56" src="https://user-images.githubusercontent.com/55786246/75543582-0ce1de00-5a1a-11ea-921c-71be3e57c211.png">

Thank you
Sara

**Comment by dgrun** [comment]
I'm not sure...
Try converting it into matrix format, and make sure that there are no NA entries. Those need to be replaced be zeroes. Also make sure that gene names are not accidentally given as first column but as row names.
Hope it works now!

**Comment by saramasarone** [comment]
The NAs were generated by the package when it created the dissimilarity matrix.. they were not in the original matrix. I have also tried to use a matrix generated by the Matrix package and it still does not work... any suggestion?

**Comment by dgrun** [comment]
This is mysterious. If you would be able to send me your input file I could figure it out. You can drop the gene names to not reveal anything about your data.

**Comment by dgrun** [comment]
You can use the email in the vignette.

**Comment by ClemensKohl** [comment]
Was there a solution on how to deal with these cases? I also run into the same problem on some data sets. As far as I can tell it is caused by the feature selection, which picks only a small subset of genes, which for a single cell happen to have identical counts and therefore standard deviation of 0.
Of course I could turn off the feature selection, but is there a more systematic way on how to avoid it?
