### ISSUE TITLE
Feel confused on RaceID vignettes

### ISSUE THREAD

**Issue by millersan** [dgrun/RaceID3_StemID2_package#6]
Hi,
I have read the vignettes on R-CRAN , but I feel confused with here

 The resulting lineage graph can be inspected and reveals the expected trajectories connecting the stem cells (cluster 2 and 3 of cycling and quiescent cells, respectively) to enterocytes (cluster 4) via transiently amplifying progenitors (cluster 1), to Paneth cells (cluster 7), and to goblet cells (cluster 6). The StemID score suggests stem cell identity for clusters 2 and 3

What puzzles me is the StemID score of cl.1 and cl.8 is higher than cl.2 and cl.3. But the StemID score suggests stem cell identity for clusters 2 and 3. 

Here is the stemid score

  | links | entropy | StemIDscore
cl.1 | 3 | 0.109705 | 0.329115
cl.2 | 3 | 0.100491 | 0.301474
cl.3 | 4 | 0.082126 | 0.328503
cl.4 | 2 | 0.098243 | 0.196486
cl.5 | 0 | 0.099537 | 0.000000
cl.6 | 1 | 0.081058 | 0.081058
cl.7 | 2 | 0.000000 | 0.000000
cl.8 | 3 | 0.131742 | 0.395227

Thank you for your help.

**Comment by dgrun** [comment]
Yes, it is true that with the settings in the vignette the StemID score of cluster 8 and 1 is comparable, and indeed a bit higher, than for clusters 2 and 3, of which we know based on marker expression (such as Lgr5) that they correspond to the stem cell population.
However, the chosen pvalue was quite high (0.1) and some of the links of cluster 8 and 1 are not very significant. Reduce the pvalue to 0.01 (in comppvalue) and you will find that the StemID score is maximal for cluster 2, which is the cluster with the highest upregulation of Lgr5.

Having said this, the StemID score only gives a guidance. I would not conclude that the cluster with the highest score always indicates the stem cell cluster. It is rather a guidance permitting to pick candidate clusters based on high StemID score. But it is required to find additional evidence based on marker genes or complementary data...

Hope this helps!

**Comment by millersan** [comment]
Thanks for your kind reply！
