### ISSUE TITLE
how to convert the SCseq to SingleCellExperiment (scater) or seurat input?

### ISSUE THREAD

**Issue by skytguuu** [dgrun/RaceID3_StemID2_package#7]
Hi,

Thanks for your developing wonderful tools for discovering the rare cell population. I have tried to use Raceid followed the online protocol (https://cran.r-project.org/web/packages/RaceID/vignettes/RaceID.html). However, I am confused that how to identify the cell cluster.  For example, I tried to find a rare cell population only expressed "zbtb16", but I didn't know how to do that. I can use the command "x <- data.frame(CELLID=names(sc@cpart),cluster=sc@cpart)" to extract the cells and their clusters. But I don't know how to find the specific expressed genes in each cluster cells. In your manual, the genes expression could be visulized by heatmap. But I found it is hard to visulize in more than thousands of cells. For example, I got the heatmap as followed:
![image](https://user-images.githubusercontent.com/25957174/92303826-35d7c280-efab-11ea-950f-29035ca9665f.png)

In this figure, it is that the target genes expressed only in small cell population. 
Hence, is any possible way to check the target genes expression in each cell population? I though violent plot or boxplot may be a better ways to visulize in each cell cluster. Can I convert the SCseq data format into SingleCellExperiment format or Seurat format, so that I can use "plotExpression"(Scater) or "VlnPlot" (Seurat) to visulize the target gene expression?

I am appreciated for your help!
Thanks!
Best,
Garen

**Comment by dgrun** [comment]
Dear Garen,

you can compare gene expression across clusters on a population level using
the fractDotPlot function. You can find this in the vignette, too. Here,
the size of the circle represents the fraction of cells in a cluster (or
sample) expressing the gene and the colour scale indicates the relative
expression levels (or z-score). Please check the help function for further
details.
RaceID doesn't include a violin plot function yet, but I will put this on
the to do list for the next update. There is also no interface to Seurat
but we will work on this as well.
I haven't tried this yet, but perhaps you could just run Seurat and
overwrite the clustering partition (seurat@meta.data$seurat_clusters) and
the dimensional reduction representation (seurat@reductions
$tsne@cell.embeddings) with sc@cpart and sc@tsne, respectively. You just
need to make sure that Seurat and RaceID are run on the same cells. This
could be done by defining a new input matrix with cells remaining after
RaceID filtering and running Seurat without any cell filtering on this
matrix...
We will also implement an interface to Seurat in the future.

Best,
Dominic
