### ISSUE TITLE
Error in if (quantile(x, 1 - pthr) < cm[i, j]) 0 else 0.5

### ISSUE THREAD

**Issue by TangentDeng** [dgrun/RaceID3_StemID2_package#8]
Hi all, when I run to this step, it showed an error like this.

> ltr <- comppvalue(ltr, pthr = 0.01, sensitive = FALSE)
Error in if (quantile(x, 1 - pthr) < cm[i, j]) 0 else 0.5 : 
  missing value where TRUE/FALSE needed

The original matrix was extracted from a Seurat object like this:
pro='S1'
sce <- CreateSeuratObject(Read10X('./scdata/allraw/day0/'),
                      pro)
sce <- NormalizeData(sce, normalization.method =  "LogNormalize",
                     scale.factor = 10000)
GetAssay(sce,assay = "RNA")
sc <- as(as.matrix(sce@assays$RNA@counts), 'sparseMatrix')
sc <- SCseq(sc)
sc <- filterdata(sc,FGenes = hbb)
hbb <- rownames(sce)[grep("^Hbb",rownames(sce))]
sc <- filterdata(sc,FGenes = hbb)
sc_p <- compdist(sc,metric="pearson")
sc_p_n20_k <- clustexp(sc_p,sat = T,clustnr = 20,FUNcluster = 'kmedoids')
plotsaturation(sc_p_n20_k,disp=FALSE)
plotjaccard(sc_p_n20_k)
sc_p_n20_k <- clustexp(sc_p_n20_k,cln=10,sat=FALSE)
sc_p_n20_k <- findoutliers(sc_p_n20_k)
plotbackground(sc_p_n20_k)
plotsensitivity(sc_p_n20_k)
plotoutlierprobs(sc_p_n20_k)
clustheatmap(sc_p_n20_k)
sc_p_n20_k <- comptsne(sc_p_n20_k)
sc_p_n20_k <- compfr(sc_p_n20_k,knn=10)
sc_p_n20_k <- compumap(sc_p_n20_k)
plotmap(sc_p_n20_k, final = T, tp = 1, fr = T, um = F, cex = 0.5)
plotexpmap(sc_p_n20_k,"Procr",logsc=TRUE,fr=F)
ltr <- Ltree(sc_p_n20_k)
ltr <- compentropy(ltr)
ltr <- projcells(ltr,cthr=5,nmode=FALSE,fr=TRUE)
ltr <- projback(ltr,pdishuf=100)
ltr <- lineagegraph(ltr)
everything is OK until comppvalue

**Comment by dgrun** [comment]
Hi, not sure what goes wrong. Could your try with another dimensional reduction, e.g., umap

ltr <- projcells(ltr,cthr=5,nmode=FALSE,um=TRUE)

or with t-SNE

ltr <- projcells(ltr,cthr=5,nmode=FALSE)

Does ltr@cdata$counts only contain NAs as off-diagonal elements?

If you provide some sample data, it would be easier to figure out.

**Comment by TangentDeng** [comment]
Thank you. I did fix the problem by setting NAs to 0.
But I run two different samples (before and after treatment) and get exactly the same result on Fruchterman-Rheingold figure like a circle! The tSNE and umap figure are normal like what seurat get. Would you mind give me some suggestions? 
![tSNE](https://user-images.githubusercontent.com/22614959/100571460-21873580-330e-11eb-91ca-670ef971c163.png)
![fr](https://user-images.githubusercontent.com/22614959/100571467-277d1680-330e-11eb-9ee2-acc55c28c75b.png)
I try to upload the figures but it looks like failure.

**Comment by TangentDeng** [comment]
![tSNE](https://user-images.githubusercontent.com/22614959/100571577-7460ed00-330e-11eb-9e12-3abbf964ed7b.png)

**Comment by TangentDeng** [comment]
![fr](https://user-images.githubusercontent.com/22614959/100571603-80e54580-330e-11eb-8d4f-71268adc3ce1.png)

**Comment by dgrun** [comment]
There is something wrong. If these are different samples you should not obtain the same maps. It is also strange that you have to replace NAs manually. They should not pop up in this object. I also never had a circle before.

If you send me sample data I could have a look...

**Comment by TangentDeng** [comment]
Dear Dr.Grün, an email from dengzhencn@163.com had sent to you and the data is in the attachment.

**Comment by TangentDeng** [comment]
> There is something wrong. If these are different samples you should not obtain the same maps. It is also strange that you have to replace NAs manually. They should not pop up in this object. I also never had a circle before.
> 
> If you send me sample data I could have a look...
Dear Dr.Grün, an email from dengzhencn@163.com had sent to you and the data is in the attachment.

**Comment by dgrun** [comment]
Hi,

I received your data. For me it works. Perhaps you only forgot to run
compfr, which is needed for running projback with fr=TRUE.

This is my code:

require(RaceID)
rownames(x) <- paste("g",1:nrow(x))
sc <- SCseq(x)
sc <- filterdata(sc)
sc <- compdist(sc)
sc <- clustexp(sc,sat=FALSE,cln=20,bootnr=1)
sc <- findoutliers(sc)
sc <- findoutliers(sc,probthr=1e-6)
sc <- compumap(sc)
sc <- compfr(sc)
sc <- comptsne(sc)
ltr <- Ltree(sc)
ltr <- compentropy(ltr)
ltr <- projcells(ltr,cthr=10,nmode=FALSE,fr=TRUE)
ltr <- projback(ltr,pdishuf=3)
ltr <- lineagegraph(ltr)
ltr <- comppvalue(ltr)
plotgraph(ltr)


I recommend running projcells with nmode=TRUE. I could not test your code
exactly, because you did not provide gene names in the data, and it was
therefore not possible to recapitulate your gene filtering.

**Comment by dgrun** [comment]
Tried again with your new data. For me there is no error message. Here the code that I ran:

x <- readRDS("sc.rds")
hbb <- rownames(x)[grep("^Hbb",rownames(x))]
sc <- SCseq(x)
sc <- filterdata(sc,FGenes = hbb)
sc <- compdist(sc)
sc <- clustexp(sc,cln=10,sat=FALSE,bootnr=1)
sc <- findoutliers(sc)
sc <- compfr(sc,knn=10)
plotmap(sc)
ltr <- Ltree(sc)
ltr <- compentropy(ltr)
ltr <- projcells(ltr,cthr=5,nmode=FALSE,fr=TRUE)
ltr <- projback(ltr,pdishuf=3)
ltr <- lineagegraph(ltr)
ltr <- comppvalue(ltr)
plotgraph(ltr)

I ran only three shuffles to reduce runtime. Should run >20. I'd still recommend running with nmode=TRUE...
